### ISSUE TITLE
Audio support in web apps

### ISSUE THREAD

**Issue by MadameMalady** [Zaedus/spider#10]
Liking Spider so far as an app, I wanted to use it for Duolingo (a language learning site and app), and spider made a webapp with a nice app icon,it opened well, but it will not play the audio for any of the words in the lessons at all.

I have used other apps to make a web app of Duolingo before, and the audio did work for me, i'm not sure what's going wrong.

**Comment by Zaedus** [comment]
Forgot to add sound to the flatpak permissions :facepalm: :facepalm:
Pushed the changes to flathub, so you can wait for an update, or edit the permissions with [Flatseal](https://flathub.org/apps/com.github.tchx84.Flatseal). Either way, thank you so much for the bug report! I'm sure many ran into this problem before you reported it.

**Comment by MadameMalady** [comment]
welcome! and yay, glad I helped
