### ISSUE TITLE
Mouse's page-back and page-forward buttons do not work

### ISSUE THREAD

**Issue by thatLeaflet** [Zaedus/spider#11]
I have a Logitech G305, which has two side buttons. One tells the browser to go back a page, the other tells the browser to go forward a page. This is a common mouse feature for medium-high end mice.

These buttons do not work for web apps. The buttons work correctly in Gnome Web, Firefox, and Chromium. Interestingly, the buttons also [don't work for another similar app, called "Web Apps"](https://codeberg.org/eyekay/webapps/issues/24).

**Comment by Zaedus** [comment]
Thanks for the report! This is a great feature to have. The current dev branch has some wonky navigation synchronization problems that I want to work out first, but this should be fixed in the upcoming release.
