### ISSUE TITLE
Better metadata

### ISSUE THREAD

**Issue by bertob** [Zaedus/spider#12]
This app only has two small issues before it passes the Flathub metadata checks:
- The summary is Title Case, it should be sentence case, i.e. `Install web apps with ease`. I'd maybe also drop the "with ease" part, it doesn't add much
-  The first screenshot shows a welcome/empty state, which is not recommended because it doesn't give people a realistic preview of what it looks like to actually use the app

Flathub metadata docs: https://docs.flathub.org/docs/for-app-authors/appdata-guidelines/quality-guidelines

**Comment by Zaedus** [comment]
Hi, thanks for reviewing this app's metadata! For that second point, the problem is the right panel not having any content, correct?

![image](https://github.com/user-attachments/assets/b625efe2-45c1-4e73-b74f-6d68cbd64ef9)

**Comment by bertob** [comment]
> the problem is the right panel not having any content, correct?

Yup, if e.g. Protonmail was selected it'd be fine

**Comment by Zaedus** [comment]
Will do! Thank you very much!
