### ISSUE TITLE
Flatpak Verification

### ISSUE THREAD

**Issue by Roman19S** [Zaedus/spider#3]
Distros like Linux Mint and Elementary OS have started hiding or otherwise discouraging the use of unverified flatpaks. More will likely follow as verified apps approach 50% of Flathub. Could you verify the flatpak on Flathub so people on these distros can find it? Here is a link to Flathub's verification documentation for app authors https://docs.flathub.org/docs/for-app-authors/verification/

**Comment by Zaedus** [comment]
All done! Thank you for the reminder!
